from sqlalchemy import Column, Index, Integer, String, Text, DateTime, ForeignKey, Enum, BigInteger, UniqueConstraint, JSON
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func
from .users import Base
class Plan(Base): __tablename__ = "plans"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); code = Column(String(50), nullable=False, unique=True); name = Column(String(255), nullable=False); description = Column(Text, nullable=True); price_paise = Column(BigInteger, nullable=False); duration_days = Column(Integer, nullable=True); status = Column(Enum("ACTIVE","INACTIVE"), nullable=False, server_default="ACTIVE"); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)
class Payment(Base): __tablename__ = "payments"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); user_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); provider = Column(String(50), nullable=False); provider_payment_id = Column(String(255), nullable=True); provider_order_id = Column(String(255), nullable=True); amount_paise = Column(BigInteger, nullable=False); currency = Column(String(3), nullable=False, server_default="INR"); status = Column(Enum("INITIATED","SUCCESS","FAILED"), nullable=False, server_default="INITIATED"); plan_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("plans.id", ondelete="SET NULL", onupdate="CASCADE"), nullable=True); idempotency_key = Column(String(255), nullable=False); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); paid_at = Column(DateTime, nullable=True); __table_args__ = (UniqueConstraint("provider","idempotency_key", name="uk_payments_idempotency"), UniqueConstraint("provider","provider_payment_id", name="uk_payments_payment_id"), UniqueConstraint("provider","provider_order_id", name="uk_payments_order_id"), Index("idx_payments_user_id", "user_id"), Index("idx_payments_status", "status"), Index("idx_payments_idempotency_key", "idempotency_key"))
class PaymentWebhookEvent(Base): __tablename__ = "payment_webhook_events"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); payment_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("payments.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); provider = Column(String(50), nullable=False); provider_event_id = Column(String(255), nullable=False); event_type = Column(String(100), nullable=False); received_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); processed_at = Column(DateTime, nullable=True); processing_status = Column(Enum("PENDING","PROCESSING","COMPLETED","FAILED"), server_default="PENDING", nullable=False); processing_attempts = Column(Integer, nullable=False, server_default="0"); max_attempts = Column(Integer, nullable=False, server_default="3"); payload = Column(JSON, nullable=True); error_message = Column(Text, nullable=True); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); __table_args__ = (UniqueConstraint("provider","provider_event_id", name="uk_webhook_provider_event"), Index("idx_webhook_events_payment_id", "payment_id"), Index("idx_webhook_events_provider_event_id", "provider_event_id"))
class Subscription(Base): __tablename__ = "subscriptions"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); user_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); plan_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("plans.id", ondelete="RESTRICT", onupdate="CASCADE"), nullable=False); payment_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("payments.id", ondelete="RESTRICT", onupdate="CASCADE"), nullable=False); start_date = Column(DateTime, server_default=func.current_timestamp(), nullable=False); end_date = Column(DateTime, nullable=True); status = Column(Enum("ACTIVE","CANCELLED","EXPIRED"), nullable=False, server_default="ACTIVE"); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)
class Entitlement(Base): __tablename__ = "entitlements"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); subscription_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("subscriptions.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); kind = Column(String(50), nullable=False); granted_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); expires_at = Column(DateTime, nullable=True); __table_args__ = (UniqueConstraint("subscription_id","kind", name="uk_entitlement_kind"),)
