from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, UniqueConstraint, Enum
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func
from .users import Base
class City(Base): __tablename__ = "cities"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); name = Column(String(255), nullable=False, unique=True); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)
class District(Base): __tablename__ = "districts"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); city_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("cities.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); name = Column(String(255), nullable=False); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); __table_args__ = (UniqueConstraint("city_id","name", name="uk_city_name"),)
class Taluk(Base): __tablename__ = "taluks"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); district_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("districts.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); name = Column(String(255), nullable=False); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); __table_args__ = (UniqueConstraint("district_id","name", name="uk_district_name"),)
class Village(Base): __tablename__ = "villages"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); taluk_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("taluks.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); name = Column(String(255), nullable=False); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False); __table_args__ = (UniqueConstraint("taluk_id","name", name="uk_taluk_name"),)
class Locality(Base): __tablename__ = "localities"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); village_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("villages.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); name = Column(String(255), nullable=False); type = Column(String(50), nullable=True); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)
class Postcode(Base): __tablename__ = "postcodes"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); locality_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("localities.id", ondelete="RESTRICT", onupdate="RESTRICT"), nullable=False); pincode = Column(String(10), nullable=False, unique=True); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)