from sqlalchemy import Column, Index, Integer, String, Text, DateTime, ForeignKey, Enum, BigInteger, JSON, UniqueConstraint
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func
from .users import Base
class PhysicalProperty(Base): __tablename__ = "physical_properties"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); postcode_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("postcodes.id", ondelete="RESTRICT", onupdate="CASCADE"), nullable=False); user_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); address_line = Column(String(500), nullable=True); area_value = Column(mysql.INTEGER(unsigned=True), nullable=True); area_unit = Column(String(20), nullable=True); bedrooms = Column(mysql.TINYINT(unsigned=True), nullable=True); bathrooms = Column(mysql.TINYINT(unsigned=True), nullable=True)
class PropertyListing(Base): __tablename__ = "property_listings"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); physical_property_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("physical_properties.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); user_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); title = Column(String(255), nullable=False); price_paise = Column(BigInteger, nullable=False); price_period = Column(Enum("TOTAL","MONTHLY"), nullable=False, server_default="TOTAL"); description = Column(Text, nullable=True); construction_status = Column(Enum("READY_TO_MOVE","UNDER_CONSTRUCTION","NEW_LAUNCH"), nullable=True); verification_status = Column(Enum("PENDING","VERIFIED"), nullable=False, server_default="PENDING"); listing_status = Column(Enum("AVAILABLE","SOLD","RENTED","LEASED"), nullable=False, server_default="AVAILABLE"); transaction_type = Column(Enum("BUY","RESALE","RENT","LEASE"), nullable=False); property_type = Column(Enum("APARTMENT","VILLA","HOUSE","COMMERCIAL","PLOT","AGRICULTURAL_LAND"), nullable=False); __table_args__ = (Index("idx_property_listings_price_paise", "price_paise"),)
class Verification(Base): __tablename__ = "verifications"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); property_listing_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("property_listings.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); attempt_no = Column(Integer, nullable=False); ruleset_version = Column(String(50), nullable=False); checks_json = Column(JSON, nullable=True); result = Column(Enum("PASS","FAIL"), nullable=False); triggered_at = Column(DateTime, nullable=False); triggered_by = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="SET NULL", onupdate="CASCADE"), nullable=True); created_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)
class PropertyMedia(Base): __tablename__ = "property_media"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); property_listing_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("property_listings.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); url = Column(String(500), nullable=False); media_type = Column(String(50), nullable=False); order_index = Column(Integer, nullable=False, server_default="0"); uploaded_by = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="SET NULL", onupdate="SET NULL"), nullable=True); uploaded_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)
class PropertyDocument(Base): __tablename__ = "property_documents"; id = Column(mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True); property_listing_id = Column(mysql.BIGINT(unsigned=True), ForeignKey("property_listings.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False); title = Column(String(255), nullable=True); url = Column(String(500), nullable=False); document_type = Column(String(50), nullable=True); uploaded_by = Column(mysql.BIGINT(unsigned=True), ForeignKey("users.id", ondelete="SET NULL", onupdate="SET NULL"), nullable=True); uploaded_at = Column(DateTime, server_default=func.current_timestamp(), nullable=False)